update HOCTU set DoUuTien = 4
select count(*) from HOCTU where DoUuTien = 3
select * from HOCTU order by DoUuTien
delete from HOCTU where TenTu = 'For ages'
Insert into HOCTU values('Hello',1)
Insert into HOCTU values('Afternoon',1)
Insert into HOCTU values('For ages',1)
Insert into HOCTU values('Evening',1)
Insert into HOCTU values('Now',1)
Insert into HOCTU values('Very well',1)
Insert into HOCTU values('Bye',1)
Insert into HOCTU values('Liberary',1)
Insert into HOCTU values('Meet',1)
Insert into HOCTU values('Glad',1)
Insert into HOCTU values('Bad',1)
Insert into HOCTU values('A long time',1)
Insert into HOCTU values('Your',1)
Insert into HOCTU values('Thanks',1)
Insert into HOCTU values('And you',1)
Insert into HOCTU values('Today',1)
Insert into HOCTU values('Later',1)
Insert into HOCTU values('spicy',1)
Insert into HOCTU values('spend',2)
Insert into HOCTU values('spell',2)
Insert into HOCTU values('special',2)
Insert into HOCTU values('speak',2)
Insert into HOCTU values('sour',2)
Insert into HOCTU values('soup',2)
Insert into HOCTU values('sound',2)
Insert into HOCTU values('so-so',2)
Insert into HOCTU values('sorry',2)
Insert into HOCTU values('sore',2)
Insert into HOCTU values('soon',2)
Insert into HOCTU values('song',2)
Insert into HOCTU values('son',2)
Insert into HOCTU values('sometimes',2)
Insert into HOCTU values('something',2)
Insert into HOCTU values('someone',2)
Insert into HOCTU values('someday',3)
Insert into HOCTU values('some',3)
Insert into HOCTU values('solution',3)
Insert into HOCTU values('software',3)
Insert into HOCTU values('soda',3)
Insert into HOCTU values('socks',3)
Insert into HOCTU values('soccer',3)
Insert into HOCTU values(' soap',3)
Insert into HOCTU values(' snow',3)
Insert into HOCTU values('sneeze',3)
Insert into HOCTU values('snack',3)
Insert into HOCTU values('smoke',3)
Insert into HOCTU values('smile',3)
Insert into HOCTU values('smell',3)
Insert into HOCTU values('smart',4)
Insert into HOCTU values('small',4)
Insert into HOCTU values('slowly',4)
Insert into HOCTU values(' slower',4)
Insert into HOCTU values('slow',4)
Insert into HOCTU values('sleep',4)
Insert into HOCTU values('sky',4)
Insert into HOCTU values('skirt',4)
Insert into HOCTU values(' skin',4)
