SELECT TOP 5 TenTu
FROM HOCTU
WHERE DoUuTien = 4
ORDER BY NEWID()
SELECT TOP 4 TenTu FROM HOCTU WHERE DoUuTien = 4 ORDER BY NEWID()
UNION 
SELECT TOP 3 TenTu FROM HOCTU WHERE DoUuTien = 3 ORDER BY NEWID()
UNION 
SELECT TOP 3 TenTu FROM HOCTU WHERE DoUuTien = 2 ORDER BY NEWID() 
UNION 
SELECT TOP 2 TenTu FROM HOCTU WHERE DoUuTien = 1 ORDER BY NEWID()
SELECT TOP 5 TenTu FROM HOCTU WHERE DoUuTien = 4 ORDER BY NEWID()